### ISSUE TITLE
GRAbB usage with multifasta of alleles

### ISSUE THREAD

**Issue by abrozzi** [b-brankovics/grabb#2]
Hi,

can GRAbB be used to assemble a bacterial genomic locus passing as input the multifasta file containing all the alleles of that locus and the reads of a whole genome sequencing run?

Thank you very much,
Alex

**Comment by b-brankovics** [comment]
Hi Alex,

Yes.

If you are only interested in the locus and not the flanking region, then I would recommend using the `--type exonerate` setting. So GRAbB stops if it finds the target region. Mostly, if the alleles can be aligned then you could use **one of them** as reference (`--ref`) and put the rest in the bait file (`--bait`), which can be a multifasta file. If you are looking at alleles that are very different from one another, then you could use the `--type multi_exonerate` setting and put all the alleles in the reference file. In this case, GRAbB will try to find all of the alleles separately. (If they are similar enough to be used as bait for each other [at least 31 bp exact match is needed for this], then multiple allele threads could return a result that is identical with the allele in you sample. Check the sequence to see what it found as homologous.)

Good luck with your work,
Balázs
