### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by hmontenegro** [b-brankovics/grabb#3]
It would be nice to have some releases, in particular, one reflecting the program as published.

**Comment by b-brankovics** [comment]
Hi @hmontenegro,

Thanks for the suggestion. I was not aware of that function. I checked out your repos, and how they look. I will add this to the repo.

You can use git to clone it, or download the zipped version of the repo. The code is the same that was used for the publication.

**Comment by b-brankovics** [comment]
The [release](https://github.com/b-brankovics/grabb/releases/tag/v1.0) has been added.
